---

# Provisioning config
enableProvisionWebfront: yes
    
# Domain name config
websiteRootName: "{{ amipoRootDomainNames.stage }}"
websiteDomainName: "www.{{ websiteRootName }}"
websiteDomainNameAliases: []

ssl_cert_parent_dir: "/etc/letsencrypt/live"

# Map of ssl certs
ssl_certs_map:
  www.amipo:
    common_name: "{{ websiteDomainName }}"
    alt_names: ["{{ websiteRootName }}", "test.{{ websiteRootName }}"]

# Env config
envName: stagging
envShortName: stage
envPs1Color: $bldpur
envPs1BgdColor: $bakpur

