---

# Provisioning config
enableProvisionWebfront: yes
    
# Clear ssh user used by ansible to not override user specified in ssh config
ansible_user: ""

# Domain name config
websiteRootName: "amipo.fr"
websiteDomainName: "www.{{ websiteRootName }}"
websiteDomainNameAliases: []

ssl_cert_parent_dir: "/etc/letsencrypt/live"

# Map of ssl certs
ssl_certs_map:
  www.amipo:
    common_name: "{{ websiteDomainName }}"
    alt_names: ["{{ websiteRootName }}"]


