---

bashStartupTemplates:
  etc:
    templates: "{{ lookup('fileglob', 'templates/etc/*.j2').split(',') }}"
    dest: /etc
    owner: root
  profiled:
    templates: "{{ lookup('fileglob', 'templates/etc_profile.d/*.j2').split(',') }}"
    dest: /etc/profile.d
    owner: root
  home:
    templates: "{{ lookup('fileglob', 'templates/home/.*.j2').split(',') }}"
    dest: /root
    owner: root

