---

# set up the bash environment

- set_fact:
    host_persistent_dir: "{{ persistentHome }}/{{ inventory_hostname }}"

- name: Ensure persistent directory exists
  file:
    path: "{{ host_persistent_dir }}"
    owner: "{{ vagrantUser }}"
    state: directory
    mode: 0777
  when: "'dev_workspace' in group_names"

- name: Deploy root env files
  template:
    src: "{{ item.src }}"
    dest: "/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: root
    mode: 0644
  loop: "{{ lookup('filetree', 'templates/chroot') }}"
  when: "item.state == 'file'"

- name: Deploy admin home env files
  template:
    src: "{{ item.src }}"
    dest: "~/{{ item.path | regex_replace('\\.j2$', '') }}"
    mode: 0644
  loop: "{{ lookup('filetree', 'templates/chroot/root') }}"
  when: "item.state == 'file'"
  become: no

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
