---

- name: Reload dnsmasq config
  shell: "/bin/bash -c 'kill -SIGHUP $(cat /var/run/lxc/dnsmasq.pid)'"
  become: yes

- name: Reload dnsmasq
  service:
    name: dnsmasq
    status: reloaded
  become: yes

- name: Restart lxc container
  shell: "lxc-stop -n {{ ctName }} || true ; lxc-start -n {{ ctName }}"
  notify: Wait for ping
  become: yes
  become_user: "{{lxcUser}}"

- name: Wait for ping
  shell: "ping -c1 {{ ctName }}.lxc"
  register: result
  until: result | succeeded
  retries: 20
  delay: 1

# Use iptables-persistent package to save rules
- name: Save iptables rules
  shell: "iptables-save > /etc/iptables/rules.v4"
  output: /etc/iptables/rules.v4
  become: yes

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
