---

# Vagrant config
controllerIp: 192.168.56.101

# Controller config
controllerUser: vagrant
controllerHome: /home/{{ controllerUser }}
ansibleHome: "{{ controllerHome }}/ansible"
#devInventory: "{{ ansibleHome }}/development_inventory"
playbooksHome: "{{ ansibleHome }}"
configHome: "{{ ansibleHome }}/config"

#ansibleHome: /home/vagrant/ansible
#inventoryHome: "{{ ansibleHome }}/{{ envName }}_inventory"
#playbooksHome: "{{ ansibleHome }}"
#configHome: "{{ ansibleHome }}/config"

# Read proxy config from a script
proxyConfigScriptPath: /etc/profile.d/proxy.sh
proxyConfig: "{{ (lookup('file', proxyConfigScriptPath) | regex_replace('\\n', '; ') + ';') | regex_replace(';+\\s*;*', ';') | regex_replace('^;$', '') }}"

