---

# SSH config
provisioningUser: manager
provisioningUserUid: 2000
provisioningKeyFilepath: "{{ controllerHome }}/.ssh/provisioning_key"
provisioningPubKey: "{{ lookup('file', provisioningKeyFilepath + '.pub') }}"

