---

nginx_conf_dir: "/etc/nginx/conf.d"
webServerSystemUser: "nginx"

webfront_architecture_map:
  www.amipo.conf:
    443:
      listen: "443 ssl http2"
      cert_name: "www.amipo"
      server_name: "{{ [websiteDomainName] + websiteDomainNameAliases }}"
      root: "/var/www/www.amipo"
      index: "index.html index.htm"

  default.conf:
    80:
      listen: "80"
      server_name: "_"
      root: "/var/www/default"
      locations:
        "/":
          try_files: "$uri $uri/ @redirect_https"
        "@redirect_https":
          return: "302 https://$host$request_uri"
    443:
      listen: "443 ssl"
      cert_name: "www.amipo"
      server_name: "_"
      root: "/var/www/default"
      locations:
        "/":
          try_files: "$uri $uri/ =404"

