---

# This playbook is responsible to deploy user profiles on hosts. 

- name: Deploy user profiles
  hosts: user_layer
  become: yes

  vars_files:
    - amipo_user_list.yml

  tasks:
    #- debug: var=item.0
    #  with_subelements:
    #    - "{{ users }}"
    #    - "groups"

    - name: Add shadow package on Alpine
      apk:
        name: shadow
      when: ansible_distribution == 'Alpine'

    - name: Create explicitly defined groups
      group:
        name: "{{ item.key }}"
        gid: "{{ item.value['gid'] }}"
      with_dict: "{{ user_groups }}"

    #- name: Create implicit groups 
    #  group:
    #    name: "{{ item.1 }}"
    #  with_subelements:
    #    - "{{ users }}"
    #    - "groups"

    - name: Create users
      user:
        name: "{{ item.key }}"
        groups: "{{ item.value.groups | default([]) }}"
        uid: "{{ item.value.uid | default('') }}"
        home: "{{ item.value.homeDir | default('/home/' + item.key) }}"
        #shell: "{{ item.value.shell | default('/bin/bash') }}"
        shell: "/bin/sh"
        generate_ssh_key: no
      with_dict: "{{ users }}"

    - name: Create authorized_keys file
      copy:
        dest: "{{ item.value.homeDir | default('/home/' + item.key) }}/.ssh/authorized_keys"
        content: ""
        force: yes
        mode: 0644
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
      with_dict: "{{ users }}"

    - name: Set internal authorized key
      shell: /bin/sh -c "cd {{ item.value.homeDir | default('/home/' + item.key) }}; echo .ssh/id_rsa.pub >> .ssh/authorized_keys"
      with_dict: "{{ users }}"


- name: Copy user public key in lobby
  hosts: lobby
  become: yes

  vars_files:
    - amipo_user_list.yml

  tasks:
    - name: Authorize user public key
      lineinfile:
        dest: "{{ item.value.homeDir | default('/home/' + item.key) }}/.ssh/authorized_keys"
        line: "{{ item.value.ssh_pub }}"
        insertafter: EOF
        mode: 0644
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
      with_dict: "{{ users }}"

  handlers:

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
