---

- name: Install and setup LXC on hosts
  hosts: lxc_hosts
  become: yes

  vars_files:
    - config-global.yml
    - "{{ configHome }}/lxc.yml"

  tasks:
    - name: Install LXC et les dependances necessaires
      apt: pkg="{{item}}" update_cache=yes cache_valid_time=3600
      with_items:
        - lxc
        - lxc-dev
        - libvirt0
        - libpam-cgroup
        - libpam-cgfs
        - bridge-utils
        - acl
        - xz-utils
        - lvm2
        - python-pip
        - dnsmasq
        - iptables-persistent

#    - name: Ajout du repo contrib
#      apt_repository:
#        repo: deb http://deb.debian.org/debian stretch main contrib non-free
#        state: present
#
#    - name: Installation de ZFS
#      apt: pkg="{{item}}" update_cache=yes cache_valid_time=3600
#        with_items:
#          - zfs-dkms 
#          - zfsutils-linux
#
#    - name: Enable zfs kernel module
#      modprobe:
#        name: zfs
#        state: present
#
#    - name: Restart zfs services
#      service:
#        name: {{item}}
#        state: restarted
#        with_items:
#          - zfs-import-cache
#          - zfs-import-scan
#          - zfs-mount
#          - zfs-share
#
#    - name: Create lxc zpool
#      command: zpool create -O compression=gzip zpool /dev/sdb -o ashift=12 -O secondarycache=all creates=/lxc

    # Upgrade pip.
    - name: Upgrade pip
      pip:
        name: pip
        extra_args: "--upgrade"

    # Install lxc-python2 package.
    - name: Install lxc-python2
      pip:
        name: lxc-python2

    - name: Create lxc lvm vol
      lvol:
        vg: "{{lxcVgName}}"
        lv: "{{lxcLvName}}"
        size: "{{lxcLvSize}}"

    - name: Create lxc FS
      filesystem:
        fstype: ext4
        dev: /dev/{{lxcVgName}}/{{lxcLvName}}

    - name: Mount lxc FS
      mount:
        name: "{{lxcVolPath}}"
        src: /dev/{{lxcVgName}}/{{lxcLvName}}
        fstype: ext4
        opts: rw
        state: mounted

    - name: Add lxc user
      user:
        name: "{{lxcUser}}"
        system: yes

    - name: Give some dir ownershif to lxc user
      file:
        path: "{{item}}"
        owner: "{{lxcUser}}"
        group: "{{lxcUser}}"
        mode: 0755
      with_items:
        - "{{lxcVolPath}}"
        - "/var/log/lxc"

    - name: Configure subgid
      lineinfile:
        dest: /etc/subgid
        regexp: "^{{lxcUser}}:"
        line: "{{lxcUser}}:1000000:65536"

    - name: Configure subuid
      lineinfile:
        dest: /etc/subuid
        regexp: "^{{lxcUser}}:"
        line: "{{lxcUser}}:1000000:65536"

    - name: Grant lxcUser to up some veth devices
      lineinfile:
        dest: /etc/lxc/lxc-usernet
        line: "{{lxcUser}} veth lxcbr0 100"

    # Use iptables-persistent package to save rules
    - name: Save iptables rules
      shell: "iptables-save > /etc/iptables/rules.v4"
      args:
        creates: /etc/iptables/rules.v4
      become: yes

    - name: Use a configuration file for lxc-net dnsmasq
      lineinfile:
        dest: /etc/default/lxc-net
        regexp: "LXC_DHCP_CONFILE="
        line: "LXC_DHCP_CONFILE=/etc/lxc/dnsmasq.conf"
      notify:
        - Restart lxc-net

    - name: Create dnsmasq.conf file
      copy:
        content: ""
        dest: /etc/lxc/dnsmasq.conf
        force: no
        owner: root
        group: root
        mode: 0644

    - name: Configure LXC dnsmasq to use a hostsfile
      lineinfile:
        dest: /etc/lxc/dnsmasq.conf
        regexp: "^dhcp-hostsfile"
        line: "dhcp-hostsfile=/etc/lxc/dnsmasq-hosts.conf"
      notify:
        - Restart lxc-net

    - name: Create dnsmasq-hosts.conf file
      copy:
        content: ""
        dest: /etc/lxc/dnsmasq-hosts.conf
        force: no
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart lxc-net

    - name: Configure lxc-net to resolve .lxc domain
      lineinfile:
        dest: /etc/default/lxc-net
        regexp: "LXC_DOMAIN="
        line: 'LXC_DOMAIN="lxc"'
      notify:
        - Restart lxc-net

    - name: Configure Host dnsmasq to resolve .lxc domain
      lineinfile:
        dest: /etc/dnsmasq.d/lxc
        regexp: "server="
        line: "server=/lxc/{{ lxcGateway }}"
      notify:
        - Restart dnsmasq

    - name: Copy lxc inventory script
      template:
        src: lxcRemoteInventory.py
        dest: /home/{{lxcUser}}/lxcRemoteInventory.py
        owner: "{{lxcUser}}"
        group: "{{lxcUser}}"
        mode: 0744

    - name: Create container groups config file
      copy:
        content: ""
        dest: "{{ lxcAnsibleGroupsFile }}"
        force: no
      become: yes
      become_user: "{{lxcUser}}"



  handlers:
    - name: Restart lxc-net
      # Attention, pas top pour le moment, car lxc-net ne restart pas dnsmasq si un CT est running !
      service:
        name: lxc-net
        state: restarted
      notify:
        - Restart dnsmasq

    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
