#! /bin/bash -e

scriptDir="$(dirname $(readlink -f $0))"
source $scriptDir/env_ansible.sh ansible-playbook $@

echo "Cleaned command: [$ansible_cleaned_command]"

vagrant ssh --tty -c "$ansible_cleaned_command" controller
