---
# List of Amipo users with their groups. Should be a secret. Could contain a group config by container, could contain a ssh pub key.

users:
  max:
    uid: 2100
    homeDir: "/home/max"
    groups: [admin, pirate]
    ssh_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJzWyirVsGYnumcs2DqM3xtDX6yO1GNg+XiwVSDMvldxL0RyPMw2tjJs+WxqrCZMDLOBB5tVqfptuY/brjdgu3NQ0kwecAZ/HMqCXEgx9aGXRFUIC22Rh4AJj67AMnx8t3p9qc0Kn4awaHvNG+9M1lQvNIFdhi55LGvEbnp8xLAIWQO1q4flXBOuZstueII1G2eQqUvzKT3uRZFL6LNrBF12QYWJNylprouLzUpyxbr25ywB79Wwg5SqJsePNeBSFxMNgMlIT2iTDHyNvPTiez6NThkMQVZJMBemSOhwCgi9gs7d3+mi+ufPDGo1zE6j/TAO+M/f2ILbVTbt4jQt35"

  b01:
    uid: 2101
    homeDir: "/home/b01"
    groups: [admin, corsair]
    ssh_pub: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJzWyirVsGYnumcs2DqM3xtDX6yO1GNg+XiwVSDMvldxL0RyPMw2tjJs+WxqrCZMDLOBB5tVqfptuY/brjdgu3NQ0kwecAZ/HMqCXEgx9aGXRFUIC22Rh4AJj67AMnx8t3p9qc0Kn4awaHvNG+9M1lQvNIFdhi55LGvEbnp8xLAIWQO1q4flXBOuZstueII1G2eQqUvzKT3uRZFL6LNrBF12QYWJNylprouLzUpyxbr25ywB79Wwg5SqJsePNeBSFxMNgMlIT2iTDHyNvPTiez6NThkMQVZJMBemSOhwCgi9gs7d3+mi+ufPDGo1zE6j/TAO+M/f2ILbVTbt4jQt35"

