---

- name: Create a LXC container
  hosts: lxc_host

  vars_files:
    - config-global.yml
    - "{{ configHome }}/config-{{ envName }}.yml"
    - "{{ configHome }}/lxc.yml"

  vars_prompt:
    - name: "containerName"
      prompt: "Container name ?"
      private: no
    - name: "containerGroups"
      prompt: "Groups list separated by commas ?"
      private: no
      default: ""
    - name: "containerDistrib"
      prompt: "Linux distribution name and version ?"
      private: no
      default: "alpine 3.7"

  roles:
    - role: lxc_container
      distribName: "{{ containerDistrib.split(' ')[0] }}"
      distribRelease: "{{ containerDistrib.split(' ')[1] }}"
      ctName: "{{ containerName }}"
      ctGroups: "{{ containerGroups.split(',') }}"

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
