---

# This playbook launch some test to verify environment is OK. 

- name: Test environment and deployment
  hosts: host
  become: yes

  vars:

  tasks:
    - name: Count 0 to 10
      shell: echo {{ item }}
      loop: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
