---

- name: Destroy a LXC container
  hosts: lxc_host

  vars_prompt:
    - name: "ctName"
      prompt: "What is the container name to destroy ?"
      private: no

  tasks:
    - name: Remove dnsmasq config
      lineinfile:
        path: /etc/lxc/dnsmasq-hosts.conf
        regexp: "^{{ item }}"
        state: absent
      become: yes
      with_items: "{{ ctName.split(' ') }}"
    
    - name: Destroy container
      shell: "lxc-stop -n {{ item }} || true; lxc-destroy -n {{ item }} || true"
      args:
        removes: "{{ lxcContainerRepo }}/{{ item }}/config"
      become: yes
      become_user: "{{ lxcUser }}"
      with_items: "{{ ctName.split(' ') }}"

    - name: Remove container groups from config file
      lineinfile:
        path: "{{ lxcAnsibleGroupsFile }}"
        regexp: "^{{ item }}:"
        state: absent
      become: yes
      become_user: "{{ lxcUser }}"
      with_items: "{{ ctName.split(' ') }}"
    
    - name: Remove files
      file:
        path: "{{ lxcContainerRepo }}/{{ item }}"
        state: absent
      become: yes
      with_items: "{{ ctName.split(' ') }}"

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
