---

# This playbook install and apply default configuration on nginx hosts. 

- name: Setup nginx
  hosts: nginx
  become: yes

  vars:
    nginx_dirs: ["/etc/nginx/conf.d", "/etc/nginx/sites-available", "/etc/nginx/sites-available"]
    template_files: ["nginx/nginx.conf"]

  tasks:
    - name: Install nginx and dependencies
      apk:
        name: "{{ item }}"
      with_items:
        - nginx
        - git
        - rsync
        - openssl
        - logrotate
      notify: Reload nginx
      tags: ["install"]

    - name: Create config directories
      file:
        path: "{{ item }}"
        state: directory
        owner: nginx
        group: nginx
        mode: u=rwX,g=rX,o=rX
      with_items: "{{ nginx_dirs }}"
      notify: Reload nginx
      tags: ["install"]

    - name: Copy nginx config files
      template:
        src: "{{ item }}"
        dest: /etc/{{ item }}
      with_items: "{{ template_files }}"
      notify: Reload nginx
      tags: ["config"]

    - name: Config directories perms
      file:
        path: "{{ item }}"
        state: directory
        owner: nginx
        group: nginx
        mode: u=rwX,g=rX,o=rX
        recurse: no
        follow: no
      notify: Reload nginx
      with_items:
        - /etc/nginx
        - /etc/nginx/conf.d
        - /etc/nginx/sites-available
      tags: ["config"]

    - name: Start nginx service
      service:
        name: nginx
        enabled: yes
        state: started

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
