---

# This playbook is responsible to install node-exporter on all hosts. 

- name: Setup prometheus node-exporter
  hosts: host
  become: yes
  gather_facts: true

  roles:
    - cloudalchemy.node-exporter

  vars:
    node_exporter_version: 0.17.0
    node_exporter_web_listen_address: 0.0.0.0:9100
    node_exporter_enabled_collectors: ["systemd"]
    node_exporter_disabled_collectors: []
    node_exporter_textfile_dir: ""

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
