---

# This playbook is responsible to setup prometheus server. 

- name: Setup prometheus server
  hosts: prometheus
  become: yes
  gather_facts: yes

  roles:
    - cloudalchemy.prometheus

  vars:
    prometheus_version: 2.5.0
    prometheus_web_listen_address: "0.0.0.0:9090"
    prometheus_web_external_url: "https://{{ websiteDomainName }}/prom"

    prometheus_targets:
      node:
        - targets:
            - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9100"
          labels:
            env: "{{ envShortName }}"
            job: node

    #prometheus_global:
          

  tasks:

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
