---

- name: Provision AMIPO dev machines
  hosts: development
  become: yes

  tasks:
    - debug: msg="Provision AMIPO dev VMs"

    - name: Wait for machine network to be up
      wait_for:
        host: 0.0.0.0
        port: 22
        timeout: 60
 
    - name: Install some packages
      package:
        name: ["vim", "rsync", "git"]
        state: present

- import_playbook: webfront_nginx_install.yml

- import_playbook: ssl_dev_root_ac_setup.yml

- import_playbook: webfront_dev_ssl_config.yml

- import_playbook: webfront_architecture_config.yml

- import_playbook: homepage_dev_workspace_deploy.yml

