---

- name: Provision controller
  hosts: controller
  become: yes

  vars:
    provisioningKeyFilepath: "{{ controllerHome }}/.ssh/provisioning_key"
    hostSshDir: "{{ controllerHome }}/.host_ssh"
    bash_profile_filepath: "{{ controllerHome }}/.bash_profile"

  tasks:

    - name: Wait for machine network to be up
      wait_for:
        host: 0.0.0.0
        port: 22
        timeout: 60

    - name: Install some packages
      package:
        name: ["dnsmasq", "vim", "rsync", "tree"]
        state: present

    - name: Configure Controller bash env
      import_tasks: tasks/bash_env_setup.yml

    - name: Add cd ansible to .profile file
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "cd {{ ansibleHome }}" 

    - name: Update PATH
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "PATH=$PATH:/vagrant/scripts" 

    - name: Config ansible role path
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "ANSIBLE_ROLES_PATH='{{ ansibleHome }}/roles'" 

    - name: Create proxy config file if it does not exists
      copy:
        content: ""
        dest: "{{ proxyConfigScriptPath }}"
        mode: 0644
        force: no

  handlers:
    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

- import_playbook: controller_ssh_config.yml

- import_playbook: controller_root_ca_dev_ssl_setup.yml

