---

- name: Provision controller
  hosts: controller
  become: yes

  vars:
    provisioningKeyFilepath: "{{ controllerHome }}/.ssh/provisioning_key"
    hostSshDir: "{{ controllerHome }}/.host_ssh"
    bash_profile_filepath: "{{ controllerHome }}/.bash_profile"

  roles:
    - amipo.shell-env-setup
    - amipo.security-hardening

  tasks:
    - name: Install some deb packages
      package:
        name: ["dnsmasq", "vim", "rsync", "tree"]
        state: present

    - name: Install some pip packages
      pip:
        name: jmespath

    - name: Ensure .profile exists
      file: 
        path: "{{ bash_profile_filepath }}" 
        state: touch

    - name: Add cd ansible to .profile file
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "cd {{ ansibleHome }}" 

    - name: Update PATH
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "PATH=$PATH:/vagrant/scripts" 

    - name: Config ansible role path
      lineinfile: 
        path: "{{ bash_profile_filepath }}" 
        line: "ANSIBLE_ROLES_PATH='{{ ansibleHome }}/roles'" 

    - name: Create proxy config file if it does not exists
      copy:
        content: ""
        dest: "{{ proxyConfigScriptPath }}"
        mode: 0644
        force: no

  handlers:
    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

- import_playbook: controller_ssh_config.yml

- import_playbook: controller_root_ca_dev_ssl_setup.yml

