---

- name: Provision AMIPO machines
  hosts: host
  become: yes

  tasks:
    - debug: msg="Provision AMIPO dev VMs"

    - name: Wait for machine network to be up
      wait_for:
        host: 0.0.0.0
        port: 22
        timeout: 60
 
    - name: Install some packages
      package:
        name: ["vim", "rsync", "git"]
        state: present

- import_playbook: webfront_letsencrypt_setup.yml

- import_playbook: webfront_nginx_install.yml

- import_playbook: webfront_dev_ssl_config.yml
  when: "'development' not in group_names"

- import_playbook: webfront_architecture_config.yml

- import_playbook: homepage_release_deploy.yml

