---

- name: Provision controller
  hosts: controller
  become: yes

  vars:
    provisioningKeyFilepath: "{{ controllerHome }}/.ssh/provisioning_key"
    hostSshDir: "{{ controllerHome }}/.host_ssh"

  tasks:

    - name: Wait for machine network to be up
      wait_for:
        host: 0.0.0.0
        port: 22
        timeout: 60

    - name: Install some packages
      package:
        name: ["dnsmasq", "vim", "rsync"]
        state: present

    - name: Add cd ansible to .profile file
      lineinfile: 
        path: "{{ controllerHome }}/.profile" 
        line: "cd {{ ansibleHome }}" 

    - name: Update PATH
      lineinfile: 
        path: "{{ controllerHome }}/.profile" 
        line: "PATH=$PATH:/vagrant/scripts" 

    - name: Config ansible role path
      lineinfile: 
        path: "{{ controllerHome }}/.profile" 
        line: "ANSIBLE_ROLES_PATH='{{ ansibleHome }}/roles'" 

    - name: Build provisioning ssh key pair
      shell: "/bin/bash -c 'ssh-keygen -b 4096 -t rsa -f {{ provisioningKeyFilepath }} -q -N \"\"'"
      args:
        creates: "{{ provisioningKeyFilepath }}"
      become_user: "{{ controllerUser }}"

    - name: Copy ssh config
      template:
        src: ssh_config.j2
        dest: "{{ controllerHome }}/.ssh/config"
        owner: "{{ controllerUser }}"
        group: "{{ controllerUser }}"
        mode: 0600

#    - name: Add route in .profile
#      lineinfile: 
#        path: "{{ controllerHome }}/.profile"
#        regexp: "ip route add {{ lxcSubnet }}"
#        line: "ip route show | grep '{{ lxcSubnet }}' > /dev/null || sudo ip route add {{ lxcSubnet }} via {{ lxcHostIp }} || true" 

    - name: Create proxy config file if it does not exists
      copy:
        content: ""
        dest: "{{ proxyConfigScriptPath }}"
        mode: 0644
        force: no

  handlers:
    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

