---

- name: Provision AMIPO machines
  hosts: host
  become: yes

  vars:

  roles:
    - amipo.shell-env-setup
    - amipo.security-hardening

  tasks:
    - debug: msg="Provision AMIPO dev VMs"

    - name: Install some packages
      package:
        name: ["vim", "rsync", "git", "tree", "htop", "bash-completion"]
        state: present
      tags: 
        - system

    - name: Add hostname in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "^127.0.0.1"
        line: "127.0.0.1 localhost {{ inventory_hostname }} {{ ansible_host }}"
      tags: 
        - system

- import_playbook: webfront_nginx_install.yml
  when: enableProvisionWebfront
  tags: 
    - webfront

- import_playbook: webfront_letsencrypt_setup.yml
  when: enableProvisionWebfront
  tags: 
    - webfront

- import_playbook: webfront_dev_ssl_config.yml
  when: "enableProvisionWebfront and 'development' in group_names"
  tags: 
    - webfront

- import_playbook: webfront_architecture_config.yml
  when: enableProvisionWebfront
  tags: 
    - webfront

- import_playbook: homepage_release_deploy.yml
  when: enableProvisionWebfront
  tags: 
    - webfront

- import_playbook: prometheus_server_setup.yml
  when: enableProvisionPrometheus
  tags: 
    - monitoring
    - prometheus

- import_playbook: node-exporter-setup.yml
  when: enableProvisionPrometheus
  tags: 
    - monitoring
    - prometheus

- import_playbook: grafana_setup.yml
  when: enableProvisionGrafana
  tags: 
    - monitoring
    - grafana

