---

# This playbook is a template wich help to start a new template. 

- name: Genereate dev SSL Root Certificate 
  hosts: controller
  become: yes
  become_user: "{{ controllerUser }}"

  vars:
    root_certificate_dir: "{{ vagrantHostDir }}/.dev_root_AC"

  tasks:
    - name: Create root AC directory
      file:
        path: "{{ root_certificate_dir }}"
        state: directory

    - name: Generate a private key
      shell: "openssl genrsa -out {{ root_certificate_dir }}/personnal_ca_key.pem 4096"
      args:
        creates: "{{ root_certificate_dir }}/personnal_ca_key.pem"

    - name: Restrict privileges of private key
      file:
        path: "{{ root_certificate_dir }}/personnal_ca_key.pem"
        state: "file"
        owner: "{{ controllerUser }}"
        mode: "0400"

    - name: Generate a certificate
      shell: "openssl req -new -key {{ root_certificate_dir }}/personnal_ca_key.pem -out {{ root_certificate_dir }}/personnal_ca_cert.pem -x509 -days 3650 -subj '/C=FR/ST=France/L=Orleans/O=Global Security/OU=IT Department/CN=amipo.fr'"
      args:
        creates: "{{ root_certificate_dir }}/personnal_ca_cert.pem"


# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
