---

- name: Setup shell env
  hosts: host
  become: yes

  vars:

  roles:
    - amipo.shell-env-setup

  tasks:
    - name: Check ssh auth
      local_action: "shell ssh -o UserKnownHostsFile=/dev/null -F {{ controllerHome }}/.ssh/config {{ inventory_hostname }} 'hostname'"
      delegate_facts: False
      register: result
      become: no
      when: "'development' in group_names"
    
