---

# This playbook config ssl for dev webfront.
# Certificates are signed by the dev root AC.

- name: Genereate dev SSL privkey, certificate and cert chain.
  hosts: webfront:&ssl_dev
  become: yes

  vars:

  tasks:
    - name: Build dev ssl certs
      include_role:
        name: amipo.devsslcerts
      vars:
        common_name: "{{ item.value.common_name }}"
        alt_names: "{{ item.value.alt_names }}"
      with_dict: "{{ ssl_certs_map }}"

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
