---

# Configure the nginx front web architecture.
# Maintain 1 file in conf.d for each server block.

- name: Configure nginx front web architecture
  hosts: webfront
  become: yes

  vars:
    server_block_template: "nginx/webFrontArchserverBlock.j2"

  tasks:
    - name: Build server block files
      template:
        src: "{{ server_block_template }}"
        dest: "{{ nginx_conf_dir }}/{{ item.key }}"
        owner: "{{ webServerSystemUser }}"
        mode: "0644"
        lstrip_blocks: yes
      with_dict: "{{ webfront_architecture_map }}"
      notify: Reload nginx

    - name: List all .conf files to check against managed files
      shell: for f in {{ nginx_conf_dir }}/*.conf; do basename $f; done
      register: contents
      changed_when: False

    - debug: msg={{ contents }}

    - name: Remove .conf files which are not managed by this playbook for security reasons
      file:
        path: "{{ nginx_conf_dir }}/{{ item }}"
        state: absent
      with_items: "{{ contents.stdout_lines }}"
      when: webfront_architecture_map[item] is not defined
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded

# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
