---

# This playbook config ssl for dev webfront.
# Certificates are signed by the dev root AC.

- name: Genereate dev SSL privkey, certificate and cert chain.
  hosts: webfront:&ssl_dev
  become: yes

  vars:
    force_ssl_cert_renew: yes

  tasks:
    - name: Build dev ssl certs
      include_role:
        name: amipo.devsslcerts
      vars:
        common_name: "{{ item.value.common_name }}"
        alt_names: "{{ item.value.alt_names }}"
        force_cert_renew: "{{ force_ssl_cert_renew }}"
      with_dict: "{{ ssl_certs_map }}"
      notify: Reload nginx

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded


# vi: tabstop=2 expandtab shiftwidth=2 softtabstop=2
