---

# Domain name config
websiteRootName: "amipo.dev"
websiteDomainName: "www.{{ websiteRootName }}"
websiteDomainNameAliases: [] #["amipo.dev"]

ssl_cert_parent_dir: "/etc/openssl/dev"

# Map of ssl certs
ssl_certs_map:
  www.amipo:
    common_name: "{{ websiteDomainName }}"
    alt_names: ["{{ websiteRootName }}", "test.{{ websiteRootName }}"]


